"use client";
import React from "react";
import { Button } from "@/components/ui/button";
import { DownloadIcon } from "lucide-react";

const DownloadSummaryButton = ({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) => {
  const handleClickDownloadAndDownloadContent = () => {
    const summaryContent = `# ${title}
    Generated Summary
    Generated on: ${new Date(createdAt).toLocaleDateString()}
    
    ${summaryText}

    Original File: ${fileName}
    Generated by Zhrnuty💖
`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    document.body.appendChild(link);
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      onClick={handleClickDownloadAndDownloadContent}
      size="sm"
      className="h-8 px-3 text-rose-600 bg-rose-200 hover:border-rose-600 hover:border 
     group-enabled:border hover:rounded-lg transition-all duration-400 ease-initial hover:text-rose-700 hover:bg-rose-50"
    >
      <DownloadIcon className="w-5 h-5 text-rose-600 mr-1" />
      Download Summary
    </Button>
  );
};

export default DownloadSummaryButton;
